### ISSUE TITLE
Buff Highlight not working for Elvui 11.46?

### ISSUE THREAD

**Issue by Urnnn** [Vekkt/ElvUI_BuffHighlight#11] opened 2020-07-21 01:29 UTC
I recently updated Elvui and am running the latest version of Elvui_BuffHighlight but it is no longer working ingame nor is it showing up under the list of Elvui plugins. Is there a potential fix for this or are we just waiting patiently for an update? Really solid plugin hope to have it working again soon.

**Comment by Vekkt** [comment] 2020-07-21 15:21
Duplicate of #6

**Closed by Vekkt** 2020-07-21 15:21 UTC
Labels: duplicate
